"""Versioned deterministic knowledge-ingestion foundation."""

from .chunks import CHUNKER_VERSION, build_chunks
from .compiler import ReferenceCompiler, validate_snapshot
from .contracts import (
    BaseSnapshot,
    Chunk,
    CompileReport,
    DocumentIR,
    DocumentRecord,
    DocumentVersion,
    IRBlock,
    QuarantineItem,
    SourceSpan,
    TombstoneDirective,
)
from .ir import DocumentIRValidationError, IR_PARSER_VERSION, build_document_ir
from .policy import POLICY_VERSION, SourcePolicy, SourcePolicyConfig
from .semantic import (
    EnrichedSnapshot,
    EvidenceBinding,
    GenerationPartReceipt,
    KnowledgeCandidate,
    KnowledgeGeneration,
    KnowledgeItem,
    ModelIdentityContract,
    ProviderIdentityEvidence,
    ProviderResponse,
    RecompileCampaign,
    SemanticCompiler,
    SemanticCompilerConfig,
    SemanticJobStore,
    SemanticPart,
    SemanticPartitionManifest,
    SemanticSourceUnit,
    build_enriched_snapshot,
    build_partitioned_request_envelopes,
    build_request_envelope,
    deprecate_item,
    extract_source_explicit,
    human_accept,
    reject_candidate,
)
from .retrieval import (
    ArtifactKnowledgeIndex,
    KnowledgeIndex,
    LikeBaselineIndex,
    SearchResponse,
    TaskContext,
)
from .semantic_provider import (
    DeepSeekV4ProProvider,
    EnvironmentSecretProvider,
    KeyringSecretProvider,
    SecretUnavailable,
    SemanticProviderError,
)

__all__ = [
    "BaseSnapshot",
    "ArtifactKnowledgeIndex",
    "CHUNKER_VERSION",
    "Chunk",
    "CompileReport",
    "DocumentIR",
    "DocumentIRValidationError",
    "DocumentRecord",
    "DocumentVersion",
    "DeepSeekV4ProProvider",
    "EnrichedSnapshot",
    "EvidenceBinding",
    "EnvironmentSecretProvider",
    "GenerationPartReceipt",
    "IRBlock",
    "IR_PARSER_VERSION",
    "KnowledgeCandidate",
    "KnowledgeGeneration",
    "KnowledgeIndex",
    "KnowledgeItem",
    "KeyringSecretProvider",
    "LikeBaselineIndex",
    "ModelIdentityContract",
    "POLICY_VERSION",
    "QuarantineItem",
    "ProviderIdentityEvidence",
    "ProviderResponse",
    "RecompileCampaign",
    "ReferenceCompiler",
    "SearchResponse",
    "SemanticCompiler",
    "SemanticCompilerConfig",
    "SemanticJobStore",
    "SemanticPart",
    "SemanticPartitionManifest",
    "SemanticProviderError",
    "SemanticSourceUnit",
    "SecretUnavailable",
    "SourcePolicy",
    "SourcePolicyConfig",
    "SourceSpan",
    "TaskContext",
    "TombstoneDirective",
    "build_chunks",
    "build_document_ir",
    "build_enriched_snapshot",
    "build_partitioned_request_envelopes",
    "build_request_envelope",
    "deprecate_item",
    "extract_source_explicit",
    "human_accept",
    "reject_candidate",
    "validate_snapshot",
]
